Web_Test/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Data.Entity;
using System.Net;
using Web_Test.Models;
using Web_Test.ViewsModels;
using System.Collections;
using System.Web.Security;

namespace Web_Test.Controllers
{
    public class TestController : Controller
    {
        private myTestEntities db = new myTestEntities();
        // GET: Test
        public ActionResult Index()
        {
            
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Index(string Content)
        {
            string value = HttpUtility.HtmlDecode(Content);
            ViewBag.text = value;
            return View();
        }
        public ActionResult SelectList()
        {
            return View(db.tbRegPageItemsSet.AsEnumerable());

        }
        //[HttpPost]
        //public ActionResult SelectList(SlectItems sItems)
        //{
        //    //tbRegSelectItemSet IsItems = new tbRegSelectItemSet();

        //    //IsItems.SelectRegPageID = sItems.sCoID;
        //    //IsItems.SelectRegPageDDate = sItems.sCoDate;
        //    //IsItems.EventID = sItems.EventID;
        //    ViewBag.list = sItems;
        //    return View("SelectList");
        //}
        public ActionResult CheackSelect(SlectItems sItems)
        {
            List<SlectItems> lsit1 = new List<SlectItems> { sItems };
            string txt = "";
            foreach (var item in lsit1)
            {
                txt += item.ToString();
            }
            TempData["list"] = txt;
            return RedirectToAction("SelectList");
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="disposing"></param>
        public ActionResult Login()
        {
            return View();
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Login(string acc, string Password)
        {

            // 登入的密碼（以 SHA1 加密）
            Password = FormsAuthentication.HashPasswordForStoringInConfigFile(Password, "SHA1");

            //這一條是去資料庫抓取輸入的帳號密碼的方法請自行實做
            //var r1 = account.GetSingleAccount(acc, Password);
            var r = db.tbUserSet.Where(i => i.UserName == acc && i.UserPWD == Password).FirstOrDefault();
            if (r == null)
            {
                TempData["Error"] = "您輸入的帳號不存在或者密碼錯誤!";
                return View();
            }

            // 登入時清空所有 Session 資料
            Session.RemoveAll();

            FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1,
              r.UserName,//你想要存放在 User.Identy.Name 的值，通常是使用者帳號
              DateTime.Now,
              DateTime.Now.AddMinutes(30),
              false,//將管理者登入的 Cookie 設定成 Session Cookie
              /*r.Rank.ToString(),*///userdata看你想存放啥
              FormsAuthentication.FormsCookiePath);

            string encTicket = FormsAuthentication.Encrypt(ticket);

            Response.Cookies.Add(new HttpCookie(FormsAuthentication.FormsCookieName, encTicket));

            return RedirectToAction("Index", "Home");

        }
        /// <summary>
        /// ///////////////
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
    public class SlectItems
    {
        public Boolean CheckStart { get; set; }
        public int SN { get; set; }
        public int RegTableCoID { get; set; }
        public string RegTableCoName { get; set; }
        public string RegTableCoType { get; set; }
        public string RegTableCoClass { get; set; }
        public string RegTableCoMemo { get; set; }
        public string RegTableCoDDate { get; set; }
    }

}

Web_Test/Views/Test/CheackSelect.cshtml
@model Web_Test.Models.tbPageSelectItemSet
@{
    ViewBag.Title = "CheackSelect";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CheackSelect</h2>

<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>

<script>
    var sItems = new Array();
    function getTest() {
        $('input:checkbox[name="sCoID"][checked=true]').each(function (i, item) {
            sItems.push($(this).val())
        })
        document.getElementById("demo").innerHTML = sItems;
    }

</script>
<input type="checkbox" name="sCoID" value="1" />報名人姓名	    <input type="hidden" name="sCoDate" value="" />
<br />
<input type="checkbox" name="sCoID" value="2" />職稱	    <input type="hidden" name="sCoDate" value="" />
<br />
<input type="checkbox" name="sCoID" value="3" />單位類別        <input type="text" name="sCoDate" value="" />
<br />
<input type="checkbox" name="sCoID" value="4" />單位名稱	    <input type="hidden" name="sCoDate" value="" />
<br />

<input type="button" value="送出" onclick="getTest();" />
<br>
<dvi id="demo"></dvi>

Web_Test/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    $(document).ready(function () {
        $("#testPanelbar").kendoPanelBar({
            expandMode: "single"
        });
    });
</script>

<div id="test_panelbar_box">
    <ul id="testPanelbar">
        <li>
            <h3 class="k-link k-state-selected">報名對象</h3>
            <div></div>
        </li>
        <li>
            <h3 class="k-link k-state-selected">活動種類</h3>
            <div></div>
        </li>
        <li>
            <h3 class="k-link k-state-selected">活動日期</h3>
            <div></div>
        </li>
        <li>
            <h3 class="k-link k-state-selected">活動地點</h3>
            <div></div>
        </li>

    </ul>

</div>

@ViewBag.text

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div hidden="hidden">
        @Html.EditorForModel()
    </div>


    @Html.Kendo().Editor().Name("Content").Tag("div").Encode(false)

    <br />

    <button id="btnSubmit3" type="submit" style="float:right" )>Save Text</button>

}

@Html.Kendo().Button().Name("mypost")
<script>
    $("#HTMLpost").click(function () { $("#HtmlTest").submit(); });


</script>

Web_Test/Views/Test/SelectList.cshtml
 @model Web_Test.ViewsModels.SlectItemsViewModel
@{
    ViewBag.Title = "SelectList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SelectList</h2>
@using (Html.BeginForm("CheackSelect", "Test"))
@*{
    foreach (var item in Model.items)
    {
        if (item.RegTableCoType == "list")
        {
            
            <input type="checkbox" name="@item.RegTableCoName" value="@item.RegTableCoID" />@Html.DisplayFor(i => item.RegTableCoMemo)
            <input type="text" name="@item.RegTableCoID" value="" />
        }
        else
        {
            <input type="checkbox" name="@item.RegTableCoName" value="@item.RegTableCoID" />@Html.DisplayFor(i => item.RegTableCoMemo)
	        <input type="hidden" name="@item.RegTableCoID" value="" /> 
	}
    <br />
}*@
    @Html.CheckBoxFor(i => )

    <input type="submit" value="送出" />
}
<br />
@TempData["list"]